In [77]:
import os
import numpy as np
import pandas as pd

from tqdm.auto import tqdm

In [102]:
data_2_dir_path = 'data\\ver_2'
data_2_modify_path = 'data\\ver_2_modify'
rpm_index_list = [900, 1200, 1500]
data_2_file_path_list = []

for file_path in os.listdir(data_2_dir_path):
    data_2_file_path_list.append(os.path.join(data_2_dir_path, file_path))

In [4]:
data_2_file_path_list

['data\\ver_2\\01_01_2024-08-06 14-03_(0)_STOP.CSV',
 'data\\ver_2\\01_02_2024-08-06 14-09_(0)_STOP.CSV',
 'data\\ver_2\\01_03_2024-08-06 14-14_(0)_STOP.CSV',
 'data\\ver_2\\02_01_2024-08-06 14-54_(0)_STOP.CSV',
 'data\\ver_2\\02_02_2024-08-06 14-58_(0)_STOP.CSV',
 'data\\ver_2\\02_03_2024-08-06 15-02_(0)_STOP.CSV',
 'data\\ver_2\\03_01_2024-08-06 15-44_(0)_STOP.CSV',
 'data\\ver_2\\03_02_2024-08-06 15-48_(0)_STOP.CSV',
 'data\\ver_2\\03_03_2024-08-06 16-04_(0)_STOP.CSV',
 'data\\ver_2\\05_01_2024-08-06 16-53_(0)_STOP.CSV',
 'data\\ver_2\\05_02_2024-08-06 16-57_(0)_STOP.CSV',
 'data\\ver_2\\05_03_2024-08-06 17-01_(0)_STOP.CSV',
 'data\\ver_2\\06_01_2024-08-07 11-04_(0)_STOP.CSV',
 'data\\ver_2\\06_02_2024-08-07 11-09_(0)_STOP.CSV',
 'data\\ver_2\\06_03_2024-08-07 11-13_(0)_STOP.CSV',
 'data\\ver_2\\08_01_2024-08-07 10-39_(0)_STOP.CSV',
 'data\\ver_2\\08_02_2024-08-07 10-44_(0)_STOP.CSV',
 'data\\ver_2\\08_03_2024-08-07 10-48_(0)_STOP.CSV',
 'data\\ver_2\\10_01_2024-08-06 17-21_(0)_STOP

In [98]:
raw_data = pd.read_csv(data_2_file_path_list[0], encoding='cp949')
raw_data

Model :            1 Unnamed: 2 Unnamed: 3 Unnamed: 4  \
0          Serial No :            1        NaN        NaN        NaN   
1               Type :          NaN        NaN        NaN        NaN   
2          Test Date :   2024-08-06        NaN        NaN        NaN   
3      Sampling Rate :       100 Hz        NaN        NaN        NaN   
4                   NaN         NaN        NaN        NaN        NaN   
...                 ...         ...        ...        ...        ...   
41552             -0.06       -0.02       0.05       0.08       0.08   
41553             -0.07       -0.05       0.03       0.09        0.1   
41554             -0.07       -0.09       0.01       0.08        0.1   
41555             -0.08       -0.14          0       0.07        0.1   
41556             -0.07       -0.17      -0.01       0.05       0.09   

      Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10  \
0            NaN        NaN        NaN        NaN        NaN         NaN   
1            NaN        NaN        NaN        NaN        NaN         NaN   
2            NaN        NaN        NaN        NaN        NaN         NaN   
3            NaN        NaN        NaN        NaN        NaN         NaN   
4            NaN        NaN        NaN        NaN        NaN         NaN   
...          ...        ...        ...        ...        ...         ...   
41552      -0.01      -0.05       0.04      29.25          0        0.27   
41553       0.01      -0.03       0.04      29.25          0        0.21   
41554       0.02      -0.01       0.04      29.25          0        0.13   
41555       0.04          0       0.03      29.26          0        0.04   
41556       0.05       0.01       0.03      29.26          0       -0.02   

      Unnamed: 11  
0             NaN  
1             NaN  
2             NaN  
3             NaN  
4             NaN  
...           ...  
41552       -2.49  
41553       -2.58  
41554       -2.72  
41555       -2.88  
41556          -3  

[41557 rows x 12 columns]

In [100]:
col_name = raw_data.iloc[6].values
col_name

array(['진공압력 1 [bar]', '메인압력 1 [bar]', '제품압력 1 [bar]', '제품압력 2 [bar]',
       '제품압력 3 [bar]', '제품압력 4 [bar]', '제품압력 5 [bar]', '회전수 [rpm]',
       '온도 [℃]', '#NAME?', '외부유량 [lpm]', '내부유량 [lpm'], dtype=object)

In [73]:
col_name = np.insert(col_name, 0, '시간 [s]')
col_name

array(['시간 [s]', '진공압력 1 [bar]', '메인압력 1 [bar]', '제품압력 1 [bar]',
       '제품압력 2 [bar]', '제품압력 3 [bar]', '제품압력 4 [bar]', '제품압력 5 [bar]',
       '회전수 [rpm]', '온도 [℃]', '#NAME?', '외부유량 [lpm]', '내부유량 [lpm'],
      dtype=object)

In [90]:
data_value = raw_data.iloc[7:, :].values
data_value = data_value.astype(np.float64)

data_value

array([[-0.1 ,  2.8 ,  2.9 , ...,  0.  ,  0.36, -2.88],
       [-0.1 ,  2.81,  2.9 , ...,  0.  ,  0.32, -3.03],
       [-0.1 ,  2.81,  2.9 , ...,  0.  ,  0.26, -3.12],
       ...,
       [-0.07, -0.09,  0.01, ...,  0.  ,  0.13, -2.72],
       [-0.08, -0.14,  0.  , ...,  0.  ,  0.04, -2.88],
       [-0.07, -0.17, -0.01, ...,  0.  , -0.02, -3.  ]])

In [61]:
time_arr = np.arange(0, data_value.shape[0])/100
time_arr

array([0.0000e+00, 1.0000e-02, 2.0000e-02, ..., 4.1547e+02, 4.1548e+02,
       4.1549e+02])

In [64]:
data_value = np.insert(data_value, 0, time_arr, axis=1)
data_value

array([[ 0.0000e+00, -1.0000e-01,  2.8000e+00, ...,  0.0000e+00,
         3.6000e-01, -2.8800e+00],
       [ 1.0000e-02, -1.0000e-01,  2.8100e+00, ...,  0.0000e+00,
         3.2000e-01, -3.0300e+00],
       [ 2.0000e-02, -1.0000e-01,  2.8100e+00, ...,  0.0000e+00,
         2.6000e-01, -3.1200e+00],
       ...,
       [ 4.1547e+02, -7.0000e-02, -9.0000e-02, ...,  0.0000e+00,
         1.3000e-01, -2.7200e+00],
       [ 4.1548e+02, -8.0000e-02, -1.4000e-01, ...,  0.0000e+00,
         4.0000e-02, -2.8800e+00],
       [ 4.1549e+02, -7.0000e-02, -1.7000e-01, ...,  0.0000e+00,
        -2.0000e-02, -3.0000e+00]])

In [66]:
data_pd = pd.DataFrame(data_value, columns=col_name)
data_pd

시간 [s]  진공압력 1 [bar]  메인압력 1 [bar]  제품압력 1 [bar]  제품압력 2 [bar]  \
0        0.00         -0.10          2.80          2.90          0.06   
1        0.01         -0.10          2.81          2.90          0.07   
2        0.02         -0.10          2.81          2.90          0.08   
3        0.03         -0.10          2.80          2.89          0.07   
4        0.04         -0.11          2.78          2.89          0.06   
...       ...           ...           ...           ...           ...   
41545  415.45         -0.06         -0.02          0.05          0.08   
41546  415.46         -0.07         -0.05          0.03          0.09   
41547  415.47         -0.07         -0.09          0.01          0.08   
41548  415.48         -0.08         -0.14          0.00          0.07   
41549  415.49         -0.07         -0.17         -0.01          0.05   

       제품압력 3 [bar]  제품압력 4 [bar]  제품압력 5 [bar]  회전수 [rpm]  온도 [℃]  #NAME?  \
0              0.05          0.04          0.06     610.38   28.66     0.0   
1              0.07          0.05          0.07     609.68   28.66     0.0   
2              0.09          0.08          0.09     605.81   28.66     0.0   
3              0.11          0.11          0.11     598.13   28.66     0.0   
4              0.12          0.14          0.13     589.30   28.66     0.0   
...             ...           ...           ...        ...     ...     ...   
41545          0.08         -0.01         -0.05       0.04   29.25     0.0   
41546          0.10          0.01         -0.03       0.04   29.25     0.0   
41547          0.10          0.02         -0.01       0.04   29.25     0.0   
41548          0.10          0.04          0.00       0.03   29.26     0.0   
41549          0.09          0.05          0.01       0.03   29.26     0.0   

       외부유량 [lpm]  내부유량 [lpm  
0            0.36      -2.88  
1            0.32      -3.03  
2            0.26      -3.12  
3            0.25      -3.12  
4            0.23      -3.03  
...           ...        ...  
41545        0.27      -2.49  
41546        0.21      -2.58  
41547        0.13      -2.72  
41548        0.04      -2.88  
41549       -0.02      -3.00  

[41550 rows x 13 columns]

In [67]:
filtered_data = data_pd[data_pd['회전수 [rpm]'] >= rpm_index_list[0]-rpm_index_list[0]*0.05]
filtered_data = filtered_data[filtered_data['회전수 [rpm]'] <= rpm_index_list[0]+rpm_index_list[0]*0.05]

In [68]:
filtered_data

시간 [s]  진공압력 1 [bar]  메인압력 1 [bar]  제품압력 1 [bar]  제품압력 2 [bar]  \
5397    53.97         -0.16          5.41          5.40         -0.02   
5398    53.98         -0.17          5.47          5.43         -0.02   
5399    53.99         -0.17          5.51          5.47         -0.01   
5400    54.00         -0.16          5.54          5.51          0.00   
5401    54.01         -0.14          5.56          5.54          0.02   
...       ...           ...           ...           ...           ...   
39275  392.75         -0.23         10.50         10.65         -0.02   
39276  392.76         -0.18         10.50         10.69         -0.03   
39277  392.77         -0.12         10.52         10.69         -0.03   
39278  392.78         -0.09         10.54         10.67         -0.03   
39279  392.79         -0.10         10.54         10.65         -0.01   

       제품압력 3 [bar]  제품압력 4 [bar]  제품압력 5 [bar]  회전수 [rpm]  온도 [℃]  #NAME?  \
5397           0.02          0.09          0.23     858.21   29.16     0.0   
5398           0.00          0.07          0.22     863.63   29.16     0.0   
5399          -0.02          0.05          0.20     868.27   29.16     0.0   
5400          -0.02          0.04          0.17     870.68   29.16     0.0   
5401           0.00          0.04          0.14     870.97   29.16     0.0   
...             ...           ...           ...        ...     ...     ...   
39275          0.01         -0.09          0.22     866.35   29.28     0.0   
39276          0.00         -0.08          0.21     866.02   29.29     0.0   
39277         -0.02         -0.07          0.19     865.15   29.29     0.0   
39278         -0.03         -0.06          0.17     862.23   29.29     0.0   
39279         -0.04         -0.05          0.17     856.35   29.28     0.0   

       외부유량 [lpm]  내부유량 [lpm  
5397       790.57      -2.98  
5398       790.33      -3.14  
5399       790.06      -3.19  
5400       789.91      -3.09  
5401       789.89      -2.88  
...           ...        ...  
39275     1824.50      -2.37  
39276     1824.66      -2.39  
39277     1824.72      -2.45  
39278     1824.68      -2.57  
39279     1824.55      -2.73  

[8825 rows x 13 columns]

In [69]:
filtered_data.to_csv('filtered_data.csv',  encoding='cp949', index=False)

In [111]:
total_iter =  len(data_2_file_path_list) * len(rpm_index_list)

with tqdm(total=total_iter, desc='Data Splitting...') as pbar:
    for data_2_file_path in data_2_file_path_list:
        for rpm_index in rpm_index_list:
            raw_data = pd.read_csv(data_2_file_path, encoding='cp949')
        
            col_name = raw_data.iloc[6].values
            col_name = np.insert(col_name, 0, '시간 [s]')
        
            data_value = raw_data.iloc[7:, :].values
            data_value = data_value.astype(np.float64)
            
            time_arr = np.arange(0, data_value.shape[0])/100
            data_value = np.insert(data_value, 0, time_arr, axis=1)
            
            data_pd = pd.DataFrame(data_value, columns=col_name)
            
            filtered_data = data_pd[data_pd['회전수 [rpm]'] >= (rpm_index-(rpm_index*0.05))]
            filtered_data = filtered_data[filtered_data['회전수 [rpm]'] <= (rpm_index+(rpm_index*0.05))]
            
            file_name, file_format = os.path.splitext(os.path.basename(data_2_file_path))
            new_file_name = os.path.join(data_2_modify_path, file_name + '_' + str(rpm_index) + file_format)

            filtered_data.to_csv(new_file_name, encoding='cp949', index=False)
            pbar.update(1)

Data Splitting...:   0%|          | 0/252 [00:00<?, ?it/s]